using DataAccess.Identity;
using DataAccess.Models;
using DataAccess.Models.Enums;

namespace ExaminationSystem.Models
{
    public class Exam : BaseModel
    {
        public  string Name { get; set; }

        public int CourseId { get; set; }
        public Course Course { get; set; }

        public ExamType Type { get; set; }

        public int NumberOfQuestions { get; set; }
        public bool IsAutoGenerated { get; set; }

        public string CreatedByInstructorId { get; set; }
        public ApplicationUser CreatedByInstructor { get; set; }

        public DateTime? StartTime { get; set; }
        public DateTime? EndTime { get; set; }

        public ICollection<ExamQuestion> ExamQuestions { get; set; }
        public ICollection<StudentExam> StudentExams { get; set; }
    }
}
