using DataAccess.Models.Enums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text;

namespace BuisnessModel.DTOs.Exam
{
    public class AddExamDto
    {
        public string Name { get; set; }
        public int CourseId { get; set; }
        public ExamType Type { get; set; }
        public int NumberOfQuestions { get; set; }
        public string InctractorId { get; set; }
        public bool IsAutoGenerated { get; set; }

    }
}
