using AutoMapper;
using BuisnessModel.DTOs.Exam;
using BuisnessModel.Interfaces;
using DataAccess.Models.Enums;
using ExaminationSystem.Models;

public class ExamService
{
    private readonly IMapper _mapper;
    private readonly IExamRepository _examRepository;

    public ExamService(IMapper mapper, IExamRepository examRepository)
    {
        _mapper = mapper;
        _examRepository = examRepository;
    }

    public async Task<List<AllExamsDTO>> GetAll()
    {
        var exams = _examRepository.GetAll();
        return _mapper.ProjectTo<AllExamsDTO>(exams).ToList();
    }

    public async Task<ExamsDTO?> GetById(int id)
    {
        if (id <= 0)
            return null;

        var exam = await _examRepository.GetByID(id);
        if (exam == null)
            return null;

        return _mapper.Map<ExamsDTO>(exam);
    }

    public async Task<bool> AddExam(AddExamDto dto)
    {
        if (string.IsNullOrWhiteSpace(dto.Name))
            return false;

        var entity = _mapper.Map<Exam>(dto);
        await _examRepository.Add(entity);

        return true;
    }

    public async Task<bool> UpdateExam(UpdateExamsDto dto)
    {
        if (dto.Id <= 0)
            return false;

        var isExists = await _examRepository.IsExist(dto.Id);
        if (!isExists)
            return false;

        var existing = await _examRepository.GetByID(dto.Id);
        if (existing == null)
            return false;

        var entity = _mapper.Map<Exam>(dto);

        var modifiedFields = new List<string>();

        if (existing.Name != dto.Name)
            modifiedFields.Add(nameof(Exam.Name));

        if (existing.Type != dto.Type)
            modifiedFields.Add(nameof(Exam.Type));

        if (existing.NumberOfQuestions != dto.NumberOfQuestions)
            modifiedFields.Add(nameof(Exam.NumberOfQuestions));

        if (existing.CreatedByInstructorId != dto.InctractorId)
            modifiedFields.Add(nameof(Exam.CreatedByInstructorId));

        if (existing.IsAutoGenerated != dto.IsAutoGenerated)
            modifiedFields.Add(nameof(Exam.IsAutoGenerated));

        if (modifiedFields.Count == 0)
            return true;

        _examRepository.UpdateInclude(entity, modifiedFields.ToArray());

        return true;
    }


    public async Task<bool> DeleteExam(int id)
    {
        if (id <= 0)
            return false;

        var exam = await _examRepository.GetByID(id);
        if (exam == null)
            return false;

        await _examRepository.Delete(id);
        return true;
    }
}
